server:
  port: 1000
spring:
  redis:
    host: 192.168.188.146
    port: 6379
  application:
    name: SCW-WEBUI
  session:
    store-type: redis
    timeout: 1800
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    com:
      offcn: debug
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 2000  #连接超时时间2秒
        readTimeout: 2000  #读超时时间2秒
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000 #设置熔断时间10秒